### ISSUE TITLE
Remove inline css

### ISSUE THREAD

**Issue by MartijnReeuwijk** [internetllama/web-app-from-scratch-18-19#1]
You should change this to a sheet instead of inline css
https://github.com/internetllama/web-app-from-scratch-18-19/blob/a4a09aa8661673f992a7fc5b94714a9b57928937/week1/index.html#L15

**Comment by MartijnReeuwijk** [comment]
Change in your Js document the inline to something like this
``
.catBreed img{
  display:block;
  width:100%;
  max-width:600px"
}
``

**Comment by internetllama** [comment]
Changes made thank you :)!
