### ISSUE TITLE
Sorting css 

### ISSUE THREAD

**Issue by MartijnReeuwijk** [internetllama/web-app-from-scratch-18-19#2]
I think you should sort your css moving the h2,h3 and body to the top of the page since they are very global in use
https://github.com/internetllama/web-app-from-scratch-18-19/blob/dd3ce412e9f8851ebac92fda1bb8c18d95ed497b/week1/public/css/styles.css#L46-L67

**Comment by internetllama** [comment]
Changes made thanks!
