### ISSUE TITLE
Remove unnecessary template literal

### ISSUE THREAD

**Issue by maanlamp** [internetllama/web-app-from-scratch-18-19#4]
https://github.com/internetllama/web-app-from-scratch-18-19/blob/aef43ad7899cf7173d5c8eaf2797fc88725604d9/week1/public/js/app.js#L9-L16

You've wrapped this `.map` inside a template literal. This is unnecessary because `.join` returns a string.

Consider this code:
```js
element.innerHTML = data.map((item, i) => `
  <div class="catBreed">
    <h1>${item.name}</h1>
    <img src="./public/img/${item.id}.jpg" style="display:block;width:100%;max-width:600px">
    <p>${item.origin}</p>
    <p>${item.temperament}</p>
  </div>
  `).join("");
```

**Comment by internetllama** [comment]
Thank you that's great, I have made the change :)
